# Generated by Django 5.1.6 on 2025-02-27 08:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                max_length=20,
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("card", "Credit/Debit Card"),
                    ("crypto", "Cryptocurrency"),
                    ("cash_on_delivery", "Cash on Delivery")
                ],
                default="mpesa",
            ),
        ),
    ]
