# Generated by Django 5.1.6 on 2025-03-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250227_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa')], default='mpesa', max_length=10),
        ),
    ]
